### ISSUE TITLE
The Fabric / Forge Jar is not remapped to intermediary

### ISSUE THREAD

**Issue by maximumpower55** [LazuriteMC/Lazurite-Toolbox#2]
Hello i am trying to make a mod using rayon when i launched my mod in production it crashed so i looked at the log file and i saw that one of toolbox's mixins is named and didn't get remapped to intermediary so i looked closer and saw that the whole toolbox jar is not getting remapped to intermediary i have a suspicion that something is wrong with your build script

**Comment by maximumpower55** [comment]
This is the same for the latest release of toolbox too

**Comment by ethanejohnsons** [comment]
Can you provide logs? Additionally, I can't guarantee the latest version of Rayon/Toolbox works outside of dev since it hasn't technically been released.

**Comment by maximumpower55** [comment]
Yep 1 second

**Comment by maximumpower55** [comment]
https://www.toptal.com/developers/hastebin/omasapipoy.yaml

**Comment by ethanejohnsons** [comment]
This should be fixed in the latest release of Rayon.

**Comment by maximumpower55** [comment]
👍
